version: '3.7'

services:
  eureka-server:
    build:
      context: ./eureka-service
    ports:
      - '8761:8761'
    restart: unless-stopped

  rabbitmq:
    image: "rabbitmq:3.9.13-management-alpine"
    hostname: "rabbit"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - "RABBITMQ_DEFAULT_USER=dst"
      - "RABBITMQ_DEFAULT_PASS=dst"