version: '3.7'

services:
  cockpit:
    container_name: cockpit
    build:
      context: ./cockpit
      args:
        - VITE_BACKEND_URL=http://localhost:8080
    ports:
      - '80:80'
    depends_on:
      - rabbitmq

  gateway:
    container_name: gateway
    build:
      context: ./gateway
    ports:
      - '8080:8080'
    restart: unless-stopped

  flowcontrol-service:
    container_name: flowcontrol-service
    build:
      context: ./flowcontrol-service
    ports:
      - '8087:8087'
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    restart: unless-stopped
    depends_on:
      - rabbitmq

  simulator-service:
    container_name: simulator-service
    build:
      context: ./simulator-service
    ports:
      - '8081:8081'
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq

  entity-service:
    container_name: entity-service
    build:
      context: ./entity-service
    ports:
      - '8889:8889'
    environment:
      - MONGO_DB_HOST=cluster0.wzcyf.mongodb.net
      - MONGO_DB_NAME=entity-service-db
      - MONGO_DB_USER=dse_2022_10
      - MONGO_DB_PWD=dse_2022_10
      - RABBIT_MQ_HOST=rabbitmq
    depends_on:
      - rabbitmq

  tracking-service:
    container_name: tracking-service
    build:
      context: ./tracking-service
    ports:
      - '8888:8888'
    environment:
      - MONGO_DB_HOST=cluster0.wzcyf.mongodb.net
      - MONGO_DB_NAME=tracking-service-db
      - MONGO_DB_USER=dse_2022_10
      - MONGO_DB_PWD=dse_2022_10
      - RABBIT_MQ_HOST=rabbitmq
    depends_on:
      - rabbitmq

  rabbitmq:
    container_name: rabbitmq
    image: 'rabbitmq:management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'
    restart: unless-stopped


