spring:
  application:
    name: gateway-service
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
    gateway:
      httpclient:
        wiretap: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: '*'
            allowedHeaders: '*'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
      routes:
        - id: entity-service
          uri: http://entity-service:8889
          predicates:
            - Path=/entities/**
        - id: tracking-service
          uri: http://tracking-service:8888
          predicates:
            - Path=/tracking/**
        - id: SIMULATOR-SERVICE
          uri: http://simulator-service:8081
          predicates:
            - Path=/simulator/**
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**, /documentation-entities/**, /documentation-tracking/**
          filters:
            - RewritePath=/documentation-entities, /entities/documentation-entities
            - RewritePath=/documentation-tracking, /tracking/documentation-tracking
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
      httpserver:
        wiretap: true

server:
  port: 8080


management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,gateway,info
  info:
    env:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    description: Gateway to our DSE Project
    version: '@project.version@'
    spring-cloud-version: '@spring-cloud.version@'
    spring-boot-version: '@project.parent.version@'

springdoc:
  swagger-ui:
    urls:
      - name: gateway
        url: /v3/api-docs
      - name: simulator
        url: /v3/api-docs/simulator
      - name: entity
        url: /documentation-entities/json
      - name: tracking
        url: /documentation-tracking/json