spring:
  application:
    name: gateway-service
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
    gateway:
      httpclient:
        wiretap: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: '*'
            allowedHeaders: '*'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
      routes:
        - id: entity-service
          uri: http://${ENTITY_SERVICE_IP:localhost}:8889
          predicates:
            - Path=/entities/**
        - id: tracking-service
          uri: http://${TRACKING_SERVICE_IP:localhost}:8888
          predicates:
            - Path=/tracking/**
        - id: SIMULATOR-SERVICE
          uri: http://${SIMULATOR_SERVICE_IP:localhost}:8081
          predicates:
            - Path=/simulator/**
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**, /documentation-entities/**, /documentation-tracking/**
          filters:
            - RewritePath=/documentation-entities, /entities/documentation-entities
            - RewritePath=/documentation-tracking, /tracking/documentation-tracking
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
        - id: api-rewrite
          uri: http://localhost:${server.port}
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<path>.*),  /$\{path}/
      httpserver:
        wiretap: true

server:
  port: 8080


management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,gateway,info
  info:
    env:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    description: Gateway to our DSE Project
    version: '@project.version@'
    spring-cloud-version: '@spring-cloud.version@'
    spring-boot-version: '@project.parent.version@'

springdoc:
  swagger-ui:
    urls:
      - name: gateway
        url: /v3/api-docs
      - name: simulator
        url: /v3/api-docs/simulator
      - name: entity
        url: /documentation-entities/json
      - name: tracking
        url: /documentation-tracking/json

health-check-services:
  services:
    entity-service: http://${ENTITY_SERVICE_IP:localhost}:8889/entities/health/
    tracking-service: http://${TRACKING_SERVICE_IP:localhost}:8888/tracking/health
    simulator-service: http://${SIMULATOR_SERVICE_IP:localhost}:8081/simulator/actuator/health
    flowcontrol-service: http://${FLOW_SERVICE_IP:localhost}:8087/flowcontrol/actuator/health