spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: '*'
            allowedHeaders: '*'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
      routes:
        - id: entity-service
          uri: lb://ENTITY-SERVICE
          predicates:
            - Path=/entities/**
        - id: tracking-service
          uri: lb://TRACKING-SERVICE
          predicates:
            - Path=/tracking/**

server:
  port: 8080
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_ADDRESS:localhost}:8761/eureka

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,gateway,info
  info:
    env:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    description: Gateway to our DSE Project
    version: '@project.version@'
    spring-cloud-version: '@spring-cloud.version@'
    spring-boot-version: '@project.parent.version@'
