spring:
  application:
    name: flowcontrol-service

server:
  port: 8087
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_ADDRESS:localhost}:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true


info:
  app:
    name: ${spring.application.name}
    description: Flow control service for our DSE Project
    version: '@project.version@'
    spring-cloud-version: '@spring-cloud.version@'
    spring-boot-version: '@project.parent.version@'


flowcontrol:
  minScanLength: 10
  maxNumberOfLights: 4
  minCarSpeed: 25
  maxCarSpeed: 130
  carStateMom: car-state
  carMom: car
  trafficLightMom: traffic-light
  trafficLightStateMom: traffic-light-state
  speedMom: car-speed
  timelapseDivider: 10