spring:
  application:
    name: simulator-service
  rabbitmq:
    host: localhost

server:
  port: 8081
  forward-headers-strategy: framework

management:
  endpoints:
    web:
      exposure:
        include: health,gateway,info
      base-path: /simulator

  info:
    env:
      enabled: true

info:
  application:
    name: ${spring.application.name}
    description: SimulatorService for our DSE Project
    version: '@project.version@'
    spring-boot-version: '@project.parent.version@'

simulator:
  minScanLength: 10
  maxNumberOfLights: 4
  minCarSpeed: 7
  maxCarSpeed: 37
  carStateTrackingMom: car-state-tracking
  carStateFlowMom: car-state-flow
  carMom: car
  trafficLightMom: traffic-light
  trafficLightStateMom: traffic-light-state
  speedMom: car-speed
  timelapseDivider: 4
  fanoutName: fanout.carState
springdoc:
  api-docs:
    path: simulator/v3/api-docs
