spring:
  application:
    name: SimulatorService
  rabbitmq:
    host: localhost

server:
  port: 8081
eureka:
  client:
    fetch-registry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_ADDRESS:localhost}:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,gateway,info

info:
  application:
    name: ${spring.application.name}
    description: SimulatorService for our DSE Project
    version: '@project.version@'
    spring-boot-version: '@project.parent.version@'
