apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: entity
  name: entity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: entity
  strategy: { }
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: entity
    spec:
      containers:
        - image: deryeger/dse-entity-service
          name: dse-entity-service
          imagePullPolicy: Never
          resources: { }
          env:
            - name: MONGO_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: dse-secrets-v2i
                  key: MONGO_DB_HOST

            - name: MONGO_DB_USER
              valueFrom:
                secretKeyRef:
                  name: dse-secrets-v2i
                  key: MONGO_DB_USER

            - name: MONGO_DB_PWD
              valueFrom:
                secretKeyRef:
                  name: dse-secrets-v2i
                  key: MONGO_DB_PWD

            - name: MONGO_DB_NAME
              value: entity-service-db
            - name: RABBIT_MQ_HOST
              value: rabbitmq-service
            - name: env.namespace
              value: default
status: { }
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: entity-service
  name: entity-service
spec:
  ports:
    - name: 8889-8889
      port: 8889
      protocol: TCP
      targetPort: 8889
  selector:
    app: entity
  type: ClusterIP
status:
  loadBalancer: { }
