apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: gateway
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  strategy: { }
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gateway
    spec:
      containers:
        - image: deryeger/dse-gateway
          name: dse-gateway
          ports:
            - containerPort: 8080
          resources: { }
          env:
            - name: env.namespace
              value: default
            - name: ENTITY_SERVICE_IP
              value: entity-service
            - name: TRACKING_SERVICE_IP
              value: tracking-service
            - name: SIMULATOR_SERVICE_IP
              value: simulator-service
            - name: FLOW_SERVICE_IP
              value: flowcontrol-service
status: { }
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: gateway-service
  name: gateway-service
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: gateway
  type: ClusterIP
status:
  loadBalancer: { }
