apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: gateway
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  strategy: { }
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gateway
    spec:
      containers:
        - image: test/dse-gateway
          name: dse-gateway
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources: { }
          env:
            - name: env.namespace
              value: default
status: { }
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: gateway-service
  name: gateway-service
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30001 #TODO: remove in production
  selector:
    app: gateway
  type: NodePort #TODO: change in production
status:
  loadBalancer: { }
